---
- name: Install Auditbeat
  package:
    name: auditbeat

- name: Configure Auditbeat
  template:
    src: auditbeat.yml.j2
    dest: /etc/auditbeat/auditbeat.yml
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart Auditbeat
  tags:
    - configuration
    - auditbeat_configuration
    - beats_configuration

- name: Setup Auditbeat in Elasticsearch
  command: >
    /bin/auditbeat setup --pipelines --index-management &&
    /bin/auditbeat version > /etc/auditbeat/pipeline_created
  run_once: true
  args:
    creates: "/etc/auditbeat/pipeline_created"
  notify:
    - Restart Auditbeat
  when:
    - auditbeat_setup | bool
    - auditbeat_output == "elasticsearch"

#- name: DEBUG
#  command: cat /etc/auditbeat/auditbeat.yml
#  register: debug
#  changed_when: false
#
#- name: DEBUG 2
#  debug:
#    var: debug.stdout
#
#- name: DEBUG 3
#  shell: systemctl start auditbeat ||cat /var/log/beats/auditbeat.log/auditbeat
#  register: auditbeatstart
#  failed_when: false
#  changed_when: false
#
#- name: DEBUG 4
#  debug:
#    var: auditbeatstart.stdout

- name: Start Auditbeat
  service:
    name: auditbeat
    state: started
    enabled: true
  when: auditbeat_enable | bool
