---
- name: create certificate directory
  file:
    path: /etc/beats/certs
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Set elasticsearch_ca variable if not already done by user
  set_fact:
    elasticsearch_ca: "{{ groups['elasticsearch'][0] }}"
  when: elasticsearch_ca is undefined
  tags:
    - certificates

- name: Fetch certificate from ca host to master
  fetch:
    src: "{{ elastic_ca_dir }}/{{ ansible_hostname }}.p12"
    dest: "/tmp/{{ ansible_hostname }}.p12"
    flat: yes
  delegate_to: "{{ elasticsearch_ca }}"
  tags:
    - certificates

- name: Copy the certificate to actual node
  copy:
    src: "/tmp/{{ ansible_hostname }}.p12"
    dest: "/etc/beats/certs/cert.p12"
    owner: root
    group: root
    mode: 0640
  tags:
    - certificates

- name: Fetch ca certificate from ca host to master
  fetch:
    src: "{{ elastic_ca_dir }}/ca.crt"
    dest: /tmp/ca.crt
    flat: yes
  delegate_to: "{{ elasticsearch_ca }}"
  tags:
    - certificates

- name: Copy the ca certificate to actual node
  copy:
    src: /tmp/ca.crt
    dest: /etc/beats/certs
    owner: root
    group: root
    mode: 0640
  tags:
    - certificates

- name: fetch Beats password
  shell: grep "PASSWORD elastic" {{ elastic_initial_passwords }} | awk {' print $4 '}
  register: beats_writer_password
  changed_when: false
  delegate_to: "{{ elasticsearch_ca }}"
