---
- name: Install Filebeat
  package:
    name: filebeat

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart Filebeat
  tags:
    - configuration
    - filebeat_configuration
    - beats_configuration

- name: Enable modules
  command: "filebeat modules enable {{ item }}"
  args:
    creates: "/etc/filebeat/modules.d/{{ item }}.yml"
  with_items: "{{ filebeat_modules }}"
  when: filebeat_modules is defined
  tags:
    - configuration
    - filebeat_configuration
    - beats_configuration

- name: Enable Ingest Pipelines
  command: >
    /bin/filebeat setup --pipelines --modules {{ item }} &&
    /bin/filebeat version > /etc/filebeat/{{ item }}_pipeline_created
  args:
    creates: "/etc/filebeat/{{ item }}_pipeline_created"
  notify:
    - Restart Filebeat
  with_items: "{{ filebeat_modules }}"
  when: filebeat_modules is defined

- name: DEBUG
  command: cat /etc/filebeat/filebeat.yml
  register: debug
  changed_when: false

- name: DEBUG 2
  debug:
    var: debug.stdout

- name: DEBUG 3
  shell: systemctl start filebeat || journalctl -xe
  register: filebeatstart
  failed_when: false
  changed_when: false

- name: DEBUG 4
  debug:
    var: filebeatstart.stdout

- name: Start Filebeat
  service:
    name: filebeat
    state: started
    enabled: true
  when: filebeat_enable | bool
