---
- name: Set elasticsearch_ca variable if not already done by user
  set_fact:
    elasticsearch_ca: "{{ groups['elasticsearch'][0] }}"
  when: elasticsearch_http_security | bool and elasticsearch_ca is undefined
  tags:
    - certificates

- import_tasks: beats-security.yml
  when: elasticsearch_http_security | bool

- import_tasks: filebeat.yml
  when: beats_filebeat | bool
