---
# handlers file for beats
#
- name: Restart Filebeat
  service:
    name: filebeat
    state: restarted
  when: filebeat_enable | bool
#
- name: Restart Auditbeat
  service:
    name: auditbeat
    state: restarted
  when: auditbeat_enable | bool
