---

- name: Check if Logstash configuration does what it should
  hosts: all
  tasks:
  - name: fetch Filebeat version
    command: "filebeat version | grep ^filebeat"
    register: filebeat_version
  - name: Fail if Filebeat has the wrong version
    fail:
      msg: "Filebeat has the wrong version"
    when: not "filebeat version 7.16.1" in filebeat_version.stdout_lines
