---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    elastic_stack_full_stack: true
    beats_filebeat: false
    beats_metricbeat: false
    beats_agent: true
    beats_fleet_server: beats-agent
  tasks:
    - name: "Include Elastics repos role"
      include_role:
        name: elastic-repos
    - name: "Include Elasticsearch role"
      include_role:
        name: elasticsearch
    - name: "Include Beats"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
