---
- name: Prepare
  hosts: all
  tasks:

    - name: Install packages for Debian
      apt:
        name:
          - git
          - gpg
          - procps
          - curl
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install unzip
      package:
        name: unzip
